User signup
wolox-training/ln-express-js pull request #3
Opened 2018-12-14 15:20 UTC by lnevado

## Summary

- Added user signup with password (alphanumeric 8+ characters) and email (wolox domain and unique) requirements.
- Added logging of custom errors and user creation.

## Trello Card
https://trello.com/c/quqSdje0/2-sign-up

2018-12-18 15:03 UTC, igna92ts reviewed
Build is failing

2019-01-04 19:42 UTC, igna92ts requested changes

2019-01-04 19:42 UTC, igna92ts commented on app/middlewares/errors.js
>    [errors.BOOK_NOT_FOUND]: 404,
remove example error

2019-01-04 19:42 UTC, igna92ts commented on test/app.js
> -'use strict';
why did you delete this?

2019-01-04 20:46 UTC, lnevado commented on app/middlewares/errors.js
>    [errors.BOOK_NOT_FOUND]: 404,
Removed example errors

2019-01-04 20:47 UTC, lnevado commented on test/app.js
> -'use strict';
Re-added it

2019-01-11 20:34 UTC, igna92ts approved these changes

2019-01-14 12:30 UTC, merged