Sign In
wolox-training/ln-express-js pull request #5
Opened 2018-12-28 15:04 UTC by lnevado

## Summary

Created user sign in using JWT, validating parameters, and tests.

## Known Issues

Token does not expire, for now.

## Trello Card

https://trello.com/c/WPTzA6Qo/3-sign-in

2018-12-31 22:21 UTC, igna92ts requested changes

2018-12-31 22:21 UTC, igna92ts commented on app/routes.js
> +  app.post('/users', validation.validateSignup, validation.validateResults, users.create);
could you try to group this in a single middleware through function compositon?

2018-12-31 22:21 UTC, igna92ts commented on app/controllers/users.js
> +    if (response) {
rather than response you could call it `user`, try to be explicit with the data you are handling when you can since in js we dont have type information to aid us on that.

2018-12-31 22:21 UTC, igna92ts commented on test/users.js
> +      .send(userWithPasswordNotMeetingRequirements)
jajajaj this is a little too explicit

2018-12-31 22:21 UTC, igna92ts commented on app/middlewares/validation.js
> +    const firstError = valErrors.array()[0].msg;
could you change this so that all errors are returned to the user??

2018-12-31 22:21 UTC, igna92ts commented on app/models/user.js
> +          throw errors.invalidEmail();
theres no need for all errors to be functions, if they are just static strings have it be a variable instead

2019-01-02 14:15 UTC, lnevado commented on app/middlewares/validation.js
> +    const firstError = valErrors.array()[0].msg;
I was trying to follow the style of `app/errors.js`:
 ```
{
  message,
  internalCode
}
```
`express-validator` provides a function that gets all validation errors, I can return that but it has extra parameters by default:
```
{
    "errors": [
        {
          message,
           
        },
        {
          location,
          param,
          value,
          msg
        }
    ]
}
```

Do you want to return all of this info or should I format it like this?:

```
{
    "errors": [
        {
          message,
          internalCode
        },
        {
          message,
          internalCode
        }
    ]
}
```

2019-01-02 14:26 UTC, lnevado commented on app/models/user.js
> +          throw errors.invalidEmail();
I had changed the `app/errors.js` file so that now the errors are functions with a default message, being able to put a more descriptive message according to the specific error.
e.g:
`app/errors.js`
```
...
exports.invalidEmail = (message = 'Invalid email, may be repeated or not belonging to a Wolox domain') =>
  internalError(message, exports.INVALID_EMAIL);
...
``` 

`app/middlewares/validation.js`
```
...
errors.invalidEmail('The email does not belong to a Wolox domain.')
...
errors.invalidEmail('The email is already in use.')
...
```

2019-01-16 16:37 UTC, igna92ts approved these changes

2019-01-16 16:55 UTC, merged